### ISSUE TITLE
"No tags file" when attempting to jump to tag

### ISSUE THREAD

**Issue by jberryman** [bitc/lushtags#13]
I'm new to using tags with Vim, so forgive me if this is obvious. I've installed lushtags according to the docs, and get a correct-looking sidebar when opening a file. 

The documentation says:

```
Tagbar is nice because it deals with creating tags automatically. There is no need to manually run commands or keep track of tag files. 
```

I assumed that meant I could just open tagbar anywhere and then do the usual jumping between files, but when I put the cursor over a token in the current file and do a `ctrl-]` I'm receiving:

```
E433: No tags file
E426: tag not found: Foo
```

Am I misunderstanding what should be happening?

**Comment by duilec** [comment]
1. To check if ctags is installed on your system, type the following command

```bash
ctags --version
```

2.  If the ctags command is not found, install universal-ctags or exuberant-ctags, type the following command

```bash
sudo apt update
sudo apt install exuberant-ctags # or sudo apt install universal-ctags
```

3. `cd` to your folder, type the following command

```
ctags -R .
```

4. `vim` to your file or folder, type `ctrl-]` to jump definition of function/data structure (backing by `ctrl-t`)
5. if your definition of function in current file, please use `gd` in vim.
