### ISSUE TITLE
I created a bug fixed repo

### ISSUE THREAD

**Issue by Saul-Mirone** [bitc/lushtags#33]
Hi guys, It seems that @bitc leave for a long time. So I created a [repo](https://github.com/Saul-Mirone/lushtags-fix) which merged the pull request added by [Vaibhav Sagar](https://github.com/vaibhavsagar) to make the lushtags work with haskell-src-exts-1.18+. If @bitc merged that pull request, the repo will be deleted.

**Comment by bitc** [comment]
@Saul-Mirone I've granted you push access to this repo
